server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: Challenge Tenpo
    version: 0.0.1-SNAPSHOT
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:challenge}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true


logging:
  level:
    com.stavaray.challenge_tenpo: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

cache:
  ttl: 30
  max-size: 1000

external:
  percentage:
    base-url: ${EXTERNAL_API_PERCENTAGE:http://localhost:8090}
